FROM node:18 AS build
WORKDIR /app
COPY frontend/package*.json .
RUN npm install
COPY frontend/ ./
RUN npm run build
FROM nginx:1.23-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf # 配置前端端口
EXPOSE 80 # 前端容器端口（与 docker-compose 映射）