server:
  port: 9000

spring:
  dataSource:
    #MySQL??
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '213729'
    url: jdbc:mysql://localhost:3306/robots?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model