spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.uwis.cn:3306/yzbc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}       # 在线数据库账号
    password: ${MYSQL_PASSWORD} # 在线数据库密码
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto

# 微信配置
wechat:
  appid: ${WECHAT_APPID}
  secret: ${WECHAT_SECRET}

# JWT配置
jwt:
  secret: ${JWT_SECRET}
  expiration: 14400000 #4小时

server:
  port: 8888
  workId: 2
  datacenterId: 5

Picture:
  url: D:/funny/images/

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: funny-data
    urlExpireTime: 31536000 #签名有效时间
    folder: tts/

# 讯飞配置
xunfei:
  api:
    host: tts-api.xfyun.cn
    path: /v2/tts
    appid: ${XUNFEI_APPID}
    api-key: ${XUNFEI_API_KEY}
    api-secret: ${XUNFEI_API_SECRET}
    voice-name: xiaoyan
    speed: 50
    volume: 50
  stt:
    host: iat-api.xfyun.cn
    path: /v2/iat
    appid: ${XUNFEI_APPID}
    api-key: ${XUNFEI_API_KEY}
    api-secret: ${XUNFEI_API_SECRET}
    language: zh_cn
    domain: iat
