name: SpringBoot+VUE CI/CD
on:
  push:
    branches: ["develop-wll"]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 构建并推送后端镜像
      - name: Build Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-backend:${{ github.sha }}
      # 构建并推送前端镜像
      - name: Build Frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue-frontend:${{ github.sha }}
      # 部署到服务器
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: us.uwis.cn
          username: 2025ug01
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/2025ug01/springboot-vue-project
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/springboot-backend:${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vue-frontend:${{ github.sha }}
            
            docker-compose down
            docker-compose up -d --build